stages:
  ### Download data ###

  # new data set, overlaps with Excel sheet, requires cleanup!
  # wget -O uswtdb_v3_1_20200717.csv https://www.sciencebase.gov/catalog/file/get/5e999f7982ce172707f6fd26?f=__disk__df%2Fd8%2F8e%2Fdfd88e79ef3438047c9af9081b2a2114fad2e892
  # Note: decommissioned turbines are not available public at all... :-/
  download_turbines:
    cmd: cd data/input/wind_turbines_usa; wget -O uswtdb_v1_3_20190107.csv https://www.sciencebase.gov/catalog/file/get/57bdfd8fe4b03fd6b7df5ff9\?f\=__disk__17%2Fd8%2Ff9%2F17d8f9c1407c32152e9ee998f5313719b2e9d4d9
    # commented out, because download link is dead and because excel file received via mail
    #outs:
    #- data/input/wind_turbines_usa
  download_wind_era5:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/download_wind_era5.py
    #deps:
    #- src
    #- scripts
    #- data/input/wind_turbines_usa
    # Note: not tracked via DVC atm because things get complicated with 115GB of data...
    #outs:
        #- data/input/wind_velocity_usa_era5

  download_gwa2:
    cmd: mkdir data/input/wind_speed_gwa2; cd data/input/wind_speed_gwa2; wget  -O gwa2_250_ws_DEFLATE.tif https://silo1.sciencedata.dk/themes/deic_theme_oc7/apps/files_sharing/public.php\?service\=files\&t\=cf5a3255eb87ca25b79aedd8afcaf570\&path\=%2FGWA2.1\&files\=gwa2_250_ws_DEFLATE.tif\&download\&g\=
    outs:
    - data/input/wind_speed_gwa2

  download_p_out_eia:
    cmd: EIA_API_KEY=$(cat eia-api-key); mkdir data/input/p_out_eia; cd data/input/p_out_eia;
      wget https://api.eia.gov/series/\?api_key\=$EIA_API_KEY\&series_id\=ELEC.GEN.WND-US-99.M
      -O ELEC.GEN.WND-US-99.M.json

        # alls states: AK AR AZ CA CO CT DE FL HI IA ID IL IN KS MA MD ME MI MN MO MT NC ND NE NH NJ NM NV NY OH OK OR PA PR RI SD TN TX UT VA VT WA WI WV WY
       # for state in IA AZ ID CA CO IN KS HI MD ME MI NH MN MO NM MT NY ND OK UT OR PA WA WV WY TX; do EIA_API_KEY=$(cat ../../../eia-api-key); mkdir data/input/p_out_eia; cd data/input/p_out_eia; wget http://api.eia.gov/series/\?api_key\=${EIA_API_KEY}\&series_id\=ELEC.GEN.WND-$state-99.M -O ELEC.GEN.WND-$state-99.M.json; done
    outs:
    - data/input/p_out_eia

  download_power_curves:
      cmd: mkdir data/input/power_curves; cd data/input/power_curves; wget https://raw.githubusercontent.com/renewables-ninja/vwf/master/power_curves/Wind%20Turbine%20Power%20Curves%20%7E%205%20\(0.01ms%20with%200.00%20w%20smoother\).csv -O power-curves-5_0_01ms_with_0w_smoother.csv
      #outs:
      #- data/input/power_curves

  ### Computations ###

  preprocess_turbines:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/preprocess_turbines.py
    deps:
    - data/input/wind_turbines_usa
    - src
    - scripts
    outs:
    - data/output/turbines
  calc_turbine_time_series:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_turbine_time_series.py
    deps:
    - data/input/p_out_eia
    - data/output/turbines
    - src
    - scripts
    outs:
    - data/output/turbine-time-series
  wind_speed:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_wind_speed.py
    deps:
    - src
    - scripts
    - data/input/wind_velocity_usa_era5
    - data/output/turbines
    outs:
    - data/interim/wind_speed
  calc_p_in:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_p_in.py
    deps:
    - data/output/turbine-time-series
    - data/input/p_out_eia
    - data/output/turbines
    - data/interim/wind_speed
    - src
    - scripts
    outs:
    - data/output/p_in
  convert_gwa_to_netcdf:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/convert_gwa_to_netcdf.py
    deps:
    - src
    - scripts
    - data/input/wind_speed_gwa2
    outs:
    - data/interim/wind_speed_gwa
  calc_bias_correction_gwa:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_bias_correction_gwa.py
    deps:
    - src
    - scripts
    - data/output/turbines
    - data/interim/wind_speed
    - data/interim/wind_speed_gwa
    outs:
    - data/output/bias_correction
  calc_p_out_model:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_p_out_model.py
    deps:
    - src
    - scripts
    - data/output/turbines
    - data/output/bias_correction
    - data/interim/wind_speed
    outs:
    - data/output/p_out_model
  calc_wind_speed_distribution:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_wind_speed_distribution.py
    deps:
    - data/output/turbines
    - data/interim/wind_speed
    - src
    - scripts
    outs:
    - data/output/wind_speed_distribution
  figures:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/generate_figures.py
    deps:
    - data/output/bias_correction
    - data/output/p_in
    - data/output/p_out_model
    - data/output/turbine-time-series
    - src
    - scripts
    outs:
    - data/figures
  data_values:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_data_values.py
    deps:
    - src
    - scripts


  ### Misc ###

  run_jupyter:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD jupyter notebook #--ip 0.0.0.0 --no-browser


  ### Tests ###

  lint:
    cmd: flake8 && black --check .
    deps:
    - scripts
    - src
  unit_test:
    cmd: python3 -m pytest --cov=src --cov-report=term --cov-report=html tests
    deps:
    - scripts
    - src
  unit_test_nodep:
    # these unit tests do not require any datasets and can be run with Github Actions
    cmd: python3 -m pytest --cov=src --cov-report=term --cov-report=html tests/no_data_dependency
    deps:
    - scripts
    - src
  test_notebooks:
    cmd: PYTHONPATH=$PYTHONPATH:$PWD jupyter nbconvert --execute notebooks/0*.ipynb
      --stdout --to html > /dev/null
    deps:
    - notebooks
    - src


  ### Simulation dataset ###

  create_simulation_turbines:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/create_simulation_turbines.py
    deps:
    - src
    - scripts
    outs:
    - data-simulation/input/wind_turbines_usa
  preprocess_turbines_simulation:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/preprocess_turbines.py
    deps:
    - data-simulation/input/wind_turbines_usa
    - src
    - scripts
    outs:
    - data-simulation/output/turbines
  create_simulation_data:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/create_simulation_data.py
    deps:
    - src
    - scripts
    - data-simulation/output/turbines
    outs:
    - data-simulation/input/p_out_eia
    - data-simulation/input/wind_velocity_usa_era5
  calc_turbine_time_series_simulation:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_turbine_time_series.py
    deps:
    - data-simulation/output/turbines
    - data-simulation/input/p_out_eia
    outs:
    - data-simulation/output/turbine-time-series
  wind_speed_simulation:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_wind_speed.py
    deps:
    - data-simulation/input/p_out_eia
    - data-simulation/output/turbines
    - data-simulation/input/wind_velocity_usa_era5
    - src
    - scripts
    outs:
    - data-simulation/interim/wind_speed
  calc_p_in_simulation:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_p_in.py
    deps:
    - data-simulation/output/turbine-time-series
    - data-simulation/input/p_out_eia
    - data-simulation/output/turbines
    - data-simulation/interim/wind_speed
    - src
    outs:
    - data-simulation/output/p_in
  convert_gwa_to_netcdf_simulation:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/convert_gwa_to_netcdf.py
    deps:
    - src
    - scripts
    - data-simulation/input/wind_speed_gwa2
    outs:
    - data-simulation/interim/wind_speed_gwa
  calc_bias_correction_gwa_simulation:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_bias_correction_gwa.py
    deps:
    - src
    - scripts
    - data-simulation/output/turbines
    - data-simulation/interim/wind_speed
    - data-simulation/interim/wind_speed_gwa
    outs:
    - data-simulation/output/bias_correction
  calc_p_out_model_simulation:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_p_out_model.py
    deps:
    - src
    - scripts
    - data-simulation/output/turbines
    #- data-simulation/output/bias_correction TODO
    - data-simulation/interim/wind_speed
    outs:
    - data-simulation/output/p_out_model
  calc_wind_speed_distribution_simulation:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_wind_speed_distribution.py
    deps:
    - data-simulation/output/turbines
    - data-simulation/input/wind_turbines_usa
    - data-simulation/interim/wind_speed
    - src
    - scripts
    outs:
    - data-simulation/output/wind_speed_distribution
  checks_simulation:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/run_checks.py
    deps:
    - data-simulation/input/p_out_eia
    - data-simulation/output/turbines
    - data-simulation/interim/wind_speed
    - data-simulation/output/p_in
    - data-simulation/output/turbine-time-series
    #- data-simulation/interim/wind_speed_gwa TODO
    #- data-simulation/output/bias_correction TODO
    - data-simulation/output/p_out_model
    - src
    - scripts
  figures_simulation:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/generate_figures.py
    deps:
    - data-simulation/output/turbines
    - data-simulation/input/p_out_eia
    - data-simulation/output/p_in
    - data-simulation/output/turbine-time-series
    - src
    outs:
    - data-simulation/figures
  data_values_simulation:
    cmd: SIMULATION=1 PYTHONPATH=$PYTHONPATH:$PWD python3 scripts/calc_data_values.py
    deps:
    - src
    - scripts
  #build_arxiv:
  #  cmd: bash doc/article/build-arxiv.sh
  #  deps:
  #  - data/output/data-values
  #  - doc/figures
  #  outs:
  #  - doc/article/build
